// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWork(arg1) {
  return window['go']['main']['App']['CreateWork'](arg1);
}

export function ListWorks() {
  return window['go']['main']['App']['ListWorks']();
}

export function OpenWork(arg1) {
  return window['go']['main']['App']['OpenWork'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
