// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateWork(arg1:main.CreateWorkInput):Promise<main.WorkDTO>;

export function ListWorks():Promise<Array<main.WorkDTO>>;

export function Status():Promise<string>;
